drilldown_profile:
  target: core
  outputs:
    raw:
      type: bigquery
      method: service-account
      project: drilldown-case-study
      dataset: drilldown_raw
      location: EU
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4

    core:
      type: bigquery
      method: service-account
      project: drilldown-case-study
      dataset: drilldown_core
      location: EU
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4

    mart:
      type: bigquery
      method: service-account
      project: drilldown-case-study
      dataset: drilldown_mart
      location: EU
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
