version: 2

# -------- CORE (staging + dims + fact) --------
models:
  - name: stg_deals
    description: "Canonicalized deal stages."
    columns:
      - name: deal_stage_canonical
        tests:
          - accepted_values:
              values:
                [
                  "prospecting",
                  "qualification",
                  "proposal",
                  "negotiation",
                  "closed won",
                  "closed lost",
                  "unknown",
                ]

  - name: stg_invoices
    description: "Canonicalized invoice statuses."
    columns:
      - name: payment_status_canonical
        tests:
          - accepted_values:
              values: ["paid", "sent", "overdue", "draft", "unknown"]

  - name: dim_companies
    columns:
      - name: company_id
        tests: [unique, not_null]

  - name: dim_products
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: fact_sales
    columns:
      - name: invoice_line_id
        tests: [unique, not_null]
      - name: company_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_companies')
              field: company_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id

  # -------- MARTS --------
  - name: sales_rep_perf
    description: "Win/loss and win rate by sales rep (uses canonical stages)."
    columns:
      - name: sales_rep_id
        tests: [not_null]
      - name: win_rate
        tests:
          - dbt_utils.expression_is_true:
              expression: "win_rate >= 0 and win_rate <= 1"
