version: 2

sources:
  - name: raw
    schema: drilldown_raw
    tables:
      - name: companies
      - name: contacts
      - name: deals
        columns:
          - name: deal_stage
            tests:
              - dbt_utils.expression_is_true:
                  expression: "lower(trim(deal_stage)) in (
                    'prospecting',
                    'qualification',
                    'proposal',         -- keep original allowed
                    'proposal sent',    -- new value seen in your data
                    'negotiation',
                    'closed won',
                    'closed lost'
                  )"
      - name: invoices
        columns:
          - name: status
            tests:
              - dbt_utils.expression_is_true:
                  expression: "lower(trim(status)) in (
                    'paid','sent','overdue','closed lost','closed won','draft'
                  )"
      - name: invoice_lines
      - name: products
