version: 2

models:
  - name: sales_rep_perf
    description: "Win/loss and win rate by sales rep (uses canonical stages)."
    columns:
      - name: sales_rep_id
        tests: [not_null]
      - name: win_rate
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
